provider:
  name: faas
  gateway: http://localhost:8080

functions:
  fn1:
    lang: go
    handler: ./fn1
    image: alexellis/fn1:0.1
  hipython:
    lang: python3
    handler: ./hipython
    image: hipython
